### ISSUE TITLE
Things for Stuppie's port

### ISSUE THREAD

**Issue by Bottersnike** [HTSTEM/discord-bot#10]
This is just a checklist of all the STEM-Bote features.
---
**Commands:** (For previews, run the command, prepended by `sb?` in the `#bote-spam` channel)
- [x] `help`
- [x] `usercount` NOT IN DMs
- [x] `userinfo <name, mention or fuzzy>` NOT IN DMs
- [x] `serverinfo` NOT IN DMs
- [x] `roll [sides] [number]`
- [x] `cat` (also `b1nzy`)
- [x] `dog` (also `adam`)
- [x] `randomuser` NOT IN DMs
- [x] `credits` (also `contributers`)
- [x] `google <query>` also (`g`)
- [x] `lucky <query>` Google I'm Feeling Luck SAFE MODE MUST BE ADDED TO THE URL BEFORE A GET!!
- [x] `wolfram <query>` also(`wa`, `alpha`, `wolfram_alpha`)
- [x] `md5 <str>` (also `hash`)
- [x] `sha1 <str>`
- [x] `sha256 <str>`
- [x] `sha512 <str>`
- [x] `hastebin <code>` (also `haste`, `paste`)
- [x] `moderators` (also `list_mods`, `listmods`, `mods`)
- [x] `eval` BOT OWNER ONLY
- [x] `git_pull` STAFF ONLY
- [x] `reload` DEVELOPER ONLY
- [x] `die` DEVELOPER ONLY
- [x] `yt <on/off>`

**Extras:**
- [x] Error messages get DMed to all developers [example](https://botter.doesnt-have-a.life/5gzsdjn.png) including who ran the command their display name, their username, the command, the error, the timestamp and the command-runner's avatar
- [x] The ability to reload the bot on the fly without having to restart the script (see `reload` above). This should be ran, also, after `git_pull`.
- [x] There should be messages sent to the moderator announcements channel about new CaryKH videos [example](https://botter.doesnt-have-a.life/4gxw1ko.png)
- [x] There should be a flag for running the bot to toggle between production IDs and testing IDs. The current flag is `-t` to enable testing mode, but there should probably be multiple because of multiple contributors. Testing mode changes things like the bot owner, etc. to you to facilitate easy testing.

I'll add to this and check things off when I get a chance

**Comment by Bottersnike** [comment]
DONE!

**Comment by slice** [comment]
i am expecting a cookie for my efforts

**Comment by qixils** [comment]
here :cookie:

**Comment by slice** [comment]
wow thx
