### ISSUE TITLE
Auto-post new xkcd comics to #bote-spam

### ISSUE THREAD

**Issue by qixils** [HTSTEM/discord-bot#23]
i want atleast one not-cheaty-ish hacktoberfest PR

**Comment by hanss314** [comment]
Hacktoberfest is over, go home.

**Comment by qixils** [comment]
workaround: just install an rss feed reader lol

**Comment by AlexCMueller** [comment]
for anyone interested, have some resources

- https://xkcd.com/rss.xml: rss feed for xkcd
- https://docs.python.org/3/library/xml.etree.elementtree.html: xml parser
- https://pypi.python.org/pypi/feedparser: rss feed parser (only python 2, pypi suggests conversion is easy)

**Comment by hanss314** [comment]
feedparser seems to work fine in python 3

**Comment by hanss314** [comment]
This should be done in c3609872607cb19dc95247ea60a5fcf34567ffe1, but I'll leave this open until the monday xkcd comes out.

**Comment by AlexCMueller** [comment]
a1ab6409b6117deb44f23314e412ac1b93b707c1 how do you mess this up
