### ISSUE TITLE
[joinbot] log discrim changes if username isnt changed

### ISSUE THREAD

**Issue by qixils** [HTSTEM/discord-bot#27]
yes, discord allows nitro users to change their discrim now. yes, it's silly. yes, discrims are worthless now. and yes, it would be useful to see these logged if someone changes their discrim but not their name.

**Comment by AlexCMueller** [comment]
Discrims still serve the purpose of differentiating different users with the same name: discrim/name combos are still universally unique and nitro can't override that

**Comment by adamthedog** [comment]
Should be fixed with abadee2.
