### ISSUE TITLE
sb?credits fails

### ISSUE THREAD

**Issue by qixils** [HTSTEM/discord-bot#34]
outputs `Congratulations! I can't send that message.` which seems to imply the message is over 2k characters somehow.

**Comment by Bottersnike** [comment]
Will look into and fix later today

From: Noahkiq
Sent: 31 August 2018 15:47
To: HTSTEM/DiscordBot
Cc: Subscribed
Subject: [HTSTEM/DiscordBot] sb?credits fails (#34)

outputs Congratulations! I can't send that message. which seems to imply the message is over 2k characters somehow.

**Comment by Bottersnike** [comment]
Fixed; closing
